version: '2'

services:
  mariadb:
    image: mariadb:10.1.21
    container_name: mariadb
    volumes:
      - "./docker_containers_data/mariadb/persistent_data:/var/lib/mysql"
      - "./docker_containers_data/mariadb/config:/etc/mysql "
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
  rails:
    image: ruby:2.4.0
    container_name: rails
    volumes:
      - "./application:/application"
    depends_on:
      - mariadb
    ports:
      - "3000:3000"
    restart: always
    working_dir: /application
    command: tail -f /dev/null
