version: '3.3'

volumes:
  docker_mariadb_test_persistent_data: {}

services:
  app:
    build:
      context: .
    container_name: docker_rails_test
    volumes:
      - ./:/docker_rails_test:cached
    depends_on:
      - mariadb
    restart: always
    ports:
      - '3000:3000'
    tty: true # これ重要やよ
    command: bash

  mariadb:
    image: mariadb:10.4.2
    container_name: docker_mariadb_test
    volumes:
      - docker_mariadb_test_persistent_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
